### ISSUE TITLE
Create Login Page

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/Ringer-Client-Mobile#2]
**NOTE: START AFTER ROUTING HAS BEEN COMPLETED!**

Add a page so users can log into the ringer mobile app with their Lif Account.

**Tasks**
- [x] Create design in Figma
- [x] Create UI based on Figma design 
- [ ] Add login functionality

**Comment by Superior126** [comment]
# Update
The login page is pretty much done. No functionality has been added yet.
