### ISSUE TITLE
[TRACKING ISSUE] Add Push Notification Support

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/Ringer-Client-Mobile#27]
### Description
Add support for push notifications for iOS/Android devices. This will be done using Expos push notifications API. There will be a route on Ringer Server allowing the Ringer Client to register the device to receive push notifications.

### Tasks
- [x] Lif-Platforms/New-Ringer-Server#64
- [x] Lif-Platforms/Ringer-Client-Mobile#29
- [x] https://github.com/Lif-Platforms/New-Ringer-Server/issues/65
- [x] Lif-Platforms/New-Ringer-Server#68
