### ISSUE TITLE
Create Messages Page

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/Ringer-Client-Mobile#5]
Create the page where users will send messages. This will appear when the user clicks on a direct message on the main page.

**Tasks**
- [ ] Create messages page design in Figma
- [ ] Create messages page UI based on Figma design 
- [ ] Add messaging functionality to page

**Comment by Superior126** [comment]
Finished Prototype: https://www.figma.com/proto/5PgSXtcDUG93I4hZtcfk0f/Ringer-Mobile?type=design&node-id=1-36&t=fzxfA8suoRKyLOdQ-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A36&mode=design
